export const serviceCategories = [
  {
    id: 'consultation',
    title: 'Осмотр / консультация',
    description: 'Первичный приём, диагностика и план лечения',
    services: [
      {
        id: 'consult-therapist',
        title: 'Консультация терапевта',
        duration: 30,
        price: 1200,
        description: 'Осмотр, сбор жалоб, рекомендации по лечению и профилактике.',
      },
      {
        id: 'consult-orthopedist',
        title: 'Консультация ортопеда',
        duration: 40,
        price: 1500,
        description: 'Оценка состояния зубов и выбор варианта протезирования.',
      },
      {
        id: 'consult-orthodontist',
        title: 'Консультация ортодонта',
        duration: 40,
        price: 1700,
        description: 'Анализ прикуса, фото-протокол и план коррекции.',
      },
      {
        id: 'consult-surgeon',
        title: 'Консультация хирурга',
        duration: 30,
        price: 1500,
        description: 'Подготовка к удалению, имплантации или костной пластике.',
      },
      {
        id: 'consult-implantologist',
        title: 'Консультация имплантолога',
        duration: 45,
        price: 1800,
        description: 'Оценка костной ткани, объёма работ и сроков имплантации.',
      },
      {
        id: 'consult-hygienist',
        title: 'Консультация гигиениста',
        duration: 20,
        price: 900,
        description: 'Подбор домашнего ухода и профилактики заболеваний дёсен.',
      },
      {
        id: 'consult-periodontist',
        title: 'Консультация пародонтолога',
        duration: 30,
        price: 1500,
        description: 'Диагностика состояния дёсен и пародонта.',
      },
      {
        id: 'consult-pediatric',
        title: 'Консультация детского стоматолога',
        duration: 30,
        price: 1300,
        description: 'Адаптационный приём, осмотр и рекомендации для ребёнка.',
      },
    ],
  },
  {
    id: 'diagnostics',
    title: 'Диагностика',
    description: 'Снимки, анализ прикуса и расширенная диагностика',
    services: [
      { id: 'rvg', title: 'Радиовизиография', duration: 10, price: 500, description: 'Прицельный снимок одного зуба.' },
      { id: 'opg', title: 'Ортопантомограмма', duration: 15, price: 900, description: 'Панорамный снимок обеих челюстей.' },
      { id: 'wax-up', title: 'Восковое моделирование зубов', duration: 60, price: 3200, description: 'Предварительная визуализация будущей улыбки.' },
      { id: 'axiography', title: 'Оптическая аксиография', duration: 45, price: 2800, description: 'Диагностика движений нижней челюсти.' },
      { id: 'articulator', title: 'Артикуляторная диагностика', duration: 60, price: 3500, description: 'Точное моделирование окклюзии и прикуса.' },
      { id: 'photo-protocol', title: 'Фотопротокол', duration: 20, price: 1200, description: 'Серия фото для анализа и отслеживания динамики лечения.' },
    ],
  },
  {
    id: 'treatment',
    title: 'Лечение зубов',
    description: 'Терапевтические процедуры для взрослых пациентов',
    services: [
      { id: 'caries-treatment', title: 'Лечение кариеса', duration: 60, price: 4200, description: 'Удаление поражённых тканей и восстановление формы зуба.' },
      { id: 'pulpitis-treatment', title: 'Лечение пульпита', duration: 90, price: 6800, description: 'Лечение воспаления нерва с сохранением зуба.' },
      { id: 'periodontitis-treatment', title: 'Лечение периодонтита', duration: 90, price: 7900, description: 'Обработка каналов и устранение воспаления у корня зуба.' },
      { id: 'filling', title: 'Пломбирование', duration: 45, price: 2600, description: 'Восстановление зуба современными композитными материалами.' },
      { id: 'microscope-treatment', title: 'Лечение зубов под микроскопом', duration: 90, price: 9800, description: 'Высокоточное лечение сложных случаев под увеличением.' },
    ],
  },
  {
    id: 'bite-correction',
    title: 'Исправление прикуса',
    description: 'Ортодонтическое лечение для взрослых и подростков',
    services: [
      { id: 'ortho-consultation', title: 'Консультация ортодонта', duration: 40, price: 1700, description: 'Подбор способа коррекции прикуса.' },
      { id: 'prep-ortho', title: 'Подготовка к ортодонтическому лечению', duration: 60, price: 2500, description: 'Санация полости рта и подготовка к установке системы.' },
      { id: 'braces-treatment', title: 'Лечение на брекет-системах', duration: 90, price: 12000, description: 'Установка и ведение ортодонтического лечения на брекетах.' },
      { id: 'braces', title: 'Брекеты', duration: 90, price: 38000, description: 'Комплексная установка брекет-системы.' },
      { id: 'aligners', title: 'Элайнеры', duration: 60, price: 45000, description: 'Незаметная коррекция прикуса с помощью прозрачных кап.' },
      { id: 'trainers', title: 'Трейнеры', duration: 30, price: 6500, description: 'Съёмные каппы для мягкой коррекции прикуса.' },
      { id: 'retainers', title: 'Ретейнеры', duration: 30, price: 5200, description: 'Фиксация результата после ортодонтического лечения.' },
    ],
  },
  {
    id: 'implants',
    title: 'Имплантация зубов',
    description: 'Имплантация и подготовка костной ткани',
    services: [
      { id: 'implant-installation', title: 'Установка имплантата', duration: 90, price: 28900, description: 'Хирургическая установка одного имплантата.' },
      { id: 'bone-grafting', title: 'Костная пластика', duration: 120, price: 24900, description: 'Восстановление объёма костной ткани перед имплантацией.' },
    ],
  },
  {
    id: 'pediatric',
    title: 'Детская стоматология',
    description: 'Лечение и профилактика для маленьких пациентов',
    services: [
      { id: 'children-caries-prevention', title: 'Профилактика кариеса у детей', duration: 30, price: 1800, description: 'Профилактика, герметизация и рекомендации родителям.' },
      { id: 'children-treatment', title: 'Лечение зубов у детей', duration: 45, price: 3200, description: 'Деликатное лечение молочных и постоянных зубов.' },
      { id: 'children-extraction', title: 'Удаление зубов у детей', duration: 30, price: 2500, description: 'Безопасное и бережное удаление по показаниям.' },
      { id: 'children-prosthetics', title: 'Протезирование молочных зубов', duration: 60, price: 8600, description: 'Восстановление улыбки ребёнка при ранней потере зубов.' },
      { id: 'first-visit', title: 'Подготовка ребёнка к первому визиту', duration: 30, price: 1400, description: 'Адаптационная консультация и знакомство с клиникой.' },
    ],
  },
  {
    id: 'whitening',
    title: 'Отбеливание зубов',
    description: 'Профессиональные процедуры осветления эмали',
    services: [
      { id: 'laser-whitening', title: 'Лазерное отбеливание', duration: 60, price: 14900, description: 'Осветление эмали с помощью лазера.' },
      { id: 'chemical-whitening', title: 'Химическое отбеливание', duration: 60, price: 11900, description: 'Щадящее осветление эмали профессиональными составами.' },
      { id: 'whitening-tray', title: 'Капа для отбеливания зубов', duration: 30, price: 6900, description: 'Индивидуальные каппы для домашнего отбеливания.' },
    ],
  },
  {
    id: 'hygiene',
    title: 'Профессиональная гигиена',
    description: 'Комплексная чистка и профилактика',
    services: [
      { id: 'teeth-cleaning', title: 'Чистка зубов', duration: 45, price: 3900, description: 'Комплексная гигиена полости рта.' },
      { id: 'ultrasonic-cleaning', title: 'Ультразвуковая чистка зубов', duration: 30, price: 2900, description: 'Удаление твёрдых зубных отложений.' },
      { id: 'polishing', title: 'Полировка', duration: 20, price: 1200, description: 'Сглаживание поверхности зубов после чистки.' },
      { id: 'remineralization', title: 'Реминерализация / фторирование зубов', duration: 20, price: 1500, description: 'Укрепление эмали и профилактика чувствительности.' },
      { id: 'plaque-indication', title: 'Индикация зубного налёта', duration: 15, price: 800, description: 'Окрашивание налёта для оценки гигиены.' },
    ],
  },
  {
    id: 'prosthetics',
    title: 'Протезирование',
    description: 'Восстановление зубов и жевательной функции',
    services: [
      { id: 'crown', title: 'Коронка', duration: 60, price: 18900, description: 'Изготовление и установка коронки.' },
      { id: 'bridge', title: 'Мостовидный протез', duration: 90, price: 24900, description: 'Восстановление нескольких отсутствующих зубов.' },
      { id: 'removable-prosthesis', title: 'Съёмный протез', duration: 90, price: 15900, description: 'Индивидуальный съёмный протез.' },
    ],
  },
];

export const clinics = [
  {
    id: 'clinic-1',
    name: 'Стоматология «Белый Лист»',
    address: 'Москва, ул. Профсоюзная, д. 12',
    phone: '+7 (495) 123-45-67',
    workingHours: 'Пн–Сб 08:00–21:00, Вс 09:00–18:00',
    description: 'Семейная клиника с терапией, ортодонтией и хирургией в одном месте.',
    rating: 4.9,
    reviewsCount: 184,
    coordinates: { lat: 55.6784, lng: 37.5602 },
    mapLabel: 'Профсоюзная, 12',
    highlights: ['Рентген на месте', 'Детский кабинет', 'Лечение в рассрочку'],
    services: ['consultation', 'treatment', 'hygiene', 'pediatric', 'implants'],
    doctorIds: ['doctor-1', 'doctor-2', 'doctor-4'],
    reviews: [
      { id: 'clinic-1-review-1', author: 'Марина К.', rating: 5, date: '2026-03-18', text: 'Быстро записали, администратор помог выбрать удобное время.' },
      { id: 'clinic-1-review-2', author: 'Алексей П.', rating: 5, date: '2026-02-09', text: 'Чисто, спокойно и без навязывания лишних процедур.' },
    ],
  },
  {
    id: 'clinic-2',
    name: 'Дента Парк',
    address: 'Москва, Ленинский проспект, д. 88',
    phone: '+7 (495) 222-11-33',
    workingHours: 'Ежедневно 09:00–21:00',
    description: 'Центр эстетической стоматологии, имплантации и протезирования.',
    rating: 4.8,
    reviewsCount: 142,
    coordinates: { lat: 55.6911, lng: 37.5286 },
    mapLabel: 'Ленинский проспект, 88',
    highlights: ['3D-диагностика', 'Собственная лаборатория', 'Эстетическая реставрация'],
    services: ['consultation', 'diagnostics', 'implants', 'prosthetics', 'whitening'],
    doctorIds: ['doctor-3', 'doctor-5'],
    reviews: [
      { id: 'clinic-2-review-1', author: 'Екатерина С.', rating: 5, date: '2026-03-02', text: 'Очень комфортный приём, подробно объяснили план лечения.' },
      { id: 'clinic-2-review-2', author: 'Игорь Н.', rating: 4, date: '2026-01-22', text: 'Удобная парковка и понятная навигация внутри клиники.' },
    ],
  },
  {
    id: 'clinic-3',
    name: 'Семейная стоматология «Улыбка+»',
    address: 'Москва, ул. Тверская, д. 21',
    phone: '+7 (495) 555-90-10',
    workingHours: 'Пн–Пт 08:30–20:30, Сб 09:00–17:00',
    description: 'Подходит для взрослых и детей, есть профилактика, лечение и ортодонтия.',
    rating: 4.7,
    reviewsCount: 96,
    coordinates: { lat: 55.7631, lng: 37.6093 },
    mapLabel: 'Тверская, 21',
    highlights: ['Детский приём', 'Онлайн-чат', 'Удобная запись без звонка'],
    services: ['consultation', 'hygiene', 'pediatric', 'bite-correction'],
    doctorIds: ['doctor-2', 'doctor-6'],
    reviews: [
      { id: 'clinic-3-review-1', author: 'Ольга Т.', rating: 5, date: '2026-03-28', text: 'Ходим всей семьёй, всегда доброжелательная атмосфера.' },
      { id: 'clinic-3-review-2', author: 'Дмитрий В.', rating: 4, date: '2026-02-14', text: 'Понравилось, что есть отдельный детский кабинет и акционные предложения.' },
    ],
  },
  {
    id: 'clinic-4',
    name: 'Премиум Дент',
    address: 'Москва, ул. Большая Якиманка, д. 18',
    phone: '+7 (495) 700-44-55',
    workingHours: 'Пн–Вс 10:00–22:00',
    description: 'Клиника для сложных клинических случаев, имплантации и эстетики улыбки.',
    rating: 4.9,
    reviewsCount: 127,
    coordinates: { lat: 55.7408, lng: 37.6189 },
    mapLabel: 'Большая Якиманка, 18',
    highlights: ['Седация', 'Микроскоп', 'Имплантация под ключ'],
    services: ['consultation', 'diagnostics', 'implants', 'treatment', 'prosthetics'],
    doctorIds: ['doctor-1', 'doctor-3', 'doctor-5'],
    reviews: [
      { id: 'clinic-4-review-1', author: 'Анна Л.', rating: 5, date: '2026-03-11', text: 'Современное оборудование и очень аккуратное лечение.' },
      { id: 'clinic-4-review-2', author: 'Сергей Д.', rating: 5, date: '2026-02-03', text: 'Сделали план лечения, сразу стало понятно по срокам и стоимости.' },
    ],
  },
];

export const doctors = [
  {
    id: 'doctor-1',
    fullName: 'Иванов Иван Игоревич',
    specialization: 'Стоматолог-терапевт',
    rating: 4.9,
    experienceYears: 12,
    clinicIds: ['clinic-1', 'clinic-4'],
    certificates: [
      'Эстетическая реставрация зубов, 2024',
      'Современная эндодонтия, 2023',
      'Микроскопическая стоматология, 2022',
    ],
    education: [
      'Первый МГМУ им. И. М. Сеченова, стоматологический факультет',
      'Ординатура по терапевтической стоматологии',
    ],
    skills: [
      'Лечение кариеса и пульпита',
      'Лечение под микроскопом',
      'Эстетическая реставрация',
      'Составление плана лечения',
    ],
    reviews: [
      { id: 'doctor-1-review-1', author: 'Наталья', rating: 5, date: '2026-03-16', text: 'Очень спокойно объясняет каждый этап, без лишней спешки.' },
      { id: 'doctor-1-review-2', author: 'Андрей', rating: 5, date: '2026-02-20', text: 'Лечили кариес, всё прошло комфортно и аккуратно.' },
    ],
    slotsByDate: [
      { date: '2026-04-11', label: 'Сб, 11 апреля', slots: ['09:00', '10:30', '12:00', '15:30', '18:00'] },
      { date: '2026-04-12', label: 'Вс, 12 апреля', slots: ['10:00', '11:30', '14:00', '16:30'] },
      { date: '2026-04-14', label: 'Вт, 14 апреля', slots: ['09:30', '13:00', '16:00', '19:00'] },
    ],
  },
  {
    id: 'doctor-2',
    fullName: 'Петрова Анна Сергеевна',
    specialization: 'Стоматолог-ортодонт',
    rating: 4.8,
    experienceYears: 9,
    clinicIds: ['clinic-1', 'clinic-3'],
    certificates: [
      'Ортодонтическое лечение на элайнерах, 2024',
      'Брекет-системы: планирование и ведение, 2023',
      'Функциональная диагностика прикуса, 2022',
    ],
    education: [
      'Российский университет медицины, стоматологический факультет',
      'Ординатура по ортодонтии',
    ],
    skills: [
      'Брекеты и элайнеры',
      'Планирование коррекции прикуса',
      'Лечение подростков и взрослых',
      'Фотопротокол и контроль динамики',
    ],
    reviews: [
      { id: 'doctor-2-review-1', author: 'Ксения', rating: 5, date: '2026-03-08', text: 'Подобрали понятный план лечения, всё очень профессионально.' },
      { id: 'doctor-2-review-2', author: 'Павел', rating: 5, date: '2026-01-30', text: 'После консультации стало ясно, как будет проходить лечение.' },
    ],
    slotsByDate: [
      { date: '2026-04-11', label: 'Сб, 11 апреля', slots: ['11:00', '12:30', '14:30', '17:00'] },
      { date: '2026-04-13', label: 'Пн, 13 апреля', slots: ['09:00', '11:30', '15:00', '18:30'] },
      { date: '2026-04-15', label: 'Ср, 15 апреля', slots: ['10:00', '13:30', '16:00', '19:00'] },
    ],
  },
  {
    id: 'doctor-3',
    fullName: 'Сидоров Максим Олегович',
    specialization: 'Стоматолог-хирург, имплантолог',
    rating: 4.9,
    experienceYears: 14,
    clinicIds: ['clinic-2', 'clinic-4'],
    certificates: [
      'Имплантация зубов, продвинутый курс, 2024',
      'Костная пластика и синус-лифтинг, 2023',
      'Хирургическая стоматология, 2021',
    ],
    education: [
      'Московский государственный медико-стоматологический университет',
      'Ординатура по хирургической стоматологии',
    ],
    skills: [
      'Удаление зубов любой сложности',
      'Имплантация и костная пластика',
      'Работа с КТ и 3D-планированием',
      'Седация и комфортный приём',
    ],
    reviews: [
      { id: 'doctor-3-review-1', author: 'Мария', rating: 5, date: '2026-03-21', text: 'Удаление прошло очень спокойно, всё объяснил до процедуры.' },
      { id: 'doctor-3-review-2', author: 'Евгений', rating: 5, date: '2026-02-11', text: 'Делал имплантацию, результатом доволен, сервис на высоте.' },
    ],
    slotsByDate: [
      { date: '2026-04-11', label: 'Сб, 11 апреля', slots: ['09:30', '12:00', '15:00', '18:00'] },
      { date: '2026-04-14', label: 'Вт, 14 апреля', slots: ['10:30', '13:30', '16:30'] },
      { date: '2026-04-16', label: 'Чт, 16 апреля', slots: ['09:00', '11:00', '14:00', '17:30'] },
    ],
  },
  {
    id: 'doctor-4',
    fullName: 'Кузнецова Ольга Викторовна',
    specialization: 'Детский стоматолог',
    rating: 4.8,
    experienceYears: 10,
    clinicIds: ['clinic-1'],
    certificates: [
      'Детская стоматология и адаптационный приём, 2024',
      'Психология общения с детьми, 2023',
      'Профилактика и герметизация фиссур, 2022',
    ],
    education: [
      'РНИМУ им. Н. И. Пирогова, стоматологический факультет',
      'Профессиональная переподготовка по детской стоматологии',
    ],
    skills: [
      'Первый визит без стресса',
      'Лечение молочных зубов',
      'Профилактика кариеса у детей',
      'Работа с тревожными пациентами',
    ],
    reviews: [
      { id: 'doctor-4-review-1', author: 'Оксана', rating: 5, date: '2026-03-14', text: 'Ребёнок впервые пошёл к стоматологу без слёз, это очень ценно.' },
      { id: 'doctor-4-review-2', author: 'Артём', rating: 5, date: '2026-02-25', text: 'Всё мягко, спокойно и с понятными рекомендациями для родителей.' },
    ],
    slotsByDate: [
      { date: '2026-04-12', label: 'Вс, 12 апреля', slots: ['10:00', '11:00', '13:30', '16:00'] },
      { date: '2026-04-13', label: 'Пн, 13 апреля', slots: ['09:30', '12:30', '15:30', '18:00'] },
      { date: '2026-04-15', label: 'Ср, 15 апреля', slots: ['10:30', '14:00', '17:00'] },
    ],
  },
  {
    id: 'doctor-5',
    fullName: 'Морозов Артём Павлович',
    specialization: 'Стоматолог-ортопед',
    rating: 4.7,
    experienceYears: 11,
    clinicIds: ['clinic-2', 'clinic-4'],
    certificates: [
      'Протезирование на имплантах, 2024',
      'Эстетическое протезирование, 2023',
      'Сложные клинические случаи в ортопедии, 2022',
    ],
    education: [
      'Казанский государственный медицинский университет',
      'Ординатура по ортопедической стоматологии',
    ],
    skills: [
      'Коронки и мостовидные протезы',
      'Протезирование на имплантах',
      'Восстановление прикуса и эстетики',
      'Диагностика и планирование',
    ],
    reviews: [
      { id: 'doctor-5-review-1', author: 'Виктор', rating: 5, date: '2026-03-01', text: 'Подобрали аккуратное решение, всё выглядит естественно.' },
      { id: 'doctor-5-review-2', author: 'Лилия', rating: 4, date: '2026-01-19', text: 'Подробно рассказал о вариантах и сроках изготовления.' },
    ],
    slotsByDate: [
      { date: '2026-04-11', label: 'Сб, 11 апреля', slots: ['10:00', '13:00', '16:00'] },
      { date: '2026-04-14', label: 'Вт, 14 апреля', slots: ['09:00', '12:00', '15:30', '19:00'] },
      { date: '2026-04-17', label: 'Пт, 17 апреля', slots: ['11:00', '14:30', '18:00'] },
    ],
  },
  {
    id: 'doctor-6',
    fullName: 'Фёдорова Елена Андреевна',
    specialization: 'Стоматолог-гигиенист',
    rating: 4.9,
    experienceYears: 8,
    clinicIds: ['clinic-3'],
    certificates: [
      'Профессиональная гигиена полости рта, 2024',
      'Индивидуальные программы профилактики, 2023',
      'Реминерализующая терапия, 2022',
    ],
    education: [
      'Уральский государственный медицинский университет',
      'Специализация по профилактической стоматологии',
    ],
    skills: [
      'Профгигиена и Air Flow',
      'Обучение домашней гигиене',
      'Профилактика заболеваний дёсен',
      'Работа с детьми и взрослыми',
    ],
    reviews: [
      { id: 'doctor-6-review-1', author: 'Дарья', rating: 5, date: '2026-03-26', text: 'После чистки всё подробно объяснили, стало намного понятнее, как ухаживать за зубами.' },
      { id: 'doctor-6-review-2', author: 'Илья', rating: 5, date: '2026-02-08', text: 'Очень аккуратная работа, без неприятных ощущений.' },
    ],
    slotsByDate: [
      { date: '2026-04-12', label: 'Вс, 12 апреля', slots: ['09:00', '11:00', '14:00', '17:00'] },
      { date: '2026-04-13', label: 'Пн, 13 апреля', slots: ['10:00', '12:30', '15:00', '18:30'] },
      { date: '2026-04-16', label: 'Чт, 16 апреля', slots: ['09:30', '13:00', '16:30'] },
    ],
  },
];

export const profile = {
  fullName: 'Анастасия Сергеевна Белова',
  gender: 'Женский',
  birthDate: '1992-08-17',
  phone: '+7 (916) 444-28-19',
  email: 'anastasia.belova@example.com',
  region: 'Москва',
  bonusBalance: 1460,
  cashbackPercent: 3,
  punctualityStreak: {
    current: 4,
    target: 5,
    reward: 500,
    text: 'Запишитесь и придите на приём 5 раз подряд, чтобы получить +500 бонусных баллов.',
  },
  children: [
    {
      id: 'child-1',
      name: 'Марк',
      birthDate: '2018-05-03',
      notes: 'Посещение детского стоматолога, нужен адаптационный формат.',
    },
  ],
  favoriteClinicId: 'clinic-1',
  medicalDeduction: {
    available: true,
    status: 'Можно заказать справку',
    taxRate: 13,
    documents: ['Договор на руках', 'Справка о стоимости лечения'],
  },
};

export const appointments = [
  {
    id: 'appointment-1',
    status: 'upcoming',
    type: 'Запись на приём',
    serviceId: 'caries-treatment',
    serviceName: 'Лечение кариеса',
    categoryId: 'treatment',
    clinicId: 'clinic-1',
    clinicName: 'Стоматология «Белый Лист»',
    clinicAddress: 'Москва, ул. Профсоюзная, д. 12',
    doctorId: 'doctor-1',
    doctorName: 'Иванов Иван Игоревич',
    date: '2026-04-14',
    time: '16:00',
    price: 4200,
    paid: 0,
    reminder: 'Push + SMS за 24 часа и за 2 часа до визита',
    note: 'Первичный приём, нужен осмотр и снимок',
    diagnosis: '',
  },
  {
    id: 'appointment-2',
    status: 'completed',
    type: 'Приём завершён',
    serviceId: 'teeth-cleaning',
    serviceName: 'Профессиональная гигиена',
    categoryId: 'hygiene',
    clinicId: 'clinic-3',
    clinicName: 'Семейная стоматология «Улыбка+»',
    clinicAddress: 'Москва, ул. Тверская, д. 21',
    doctorId: 'doctor-6',
    doctorName: 'Фёдорова Елена Андреевна',
    date: '2026-03-26',
    time: '11:00',
    price: 3900,
    paid: 3900,
    reminder: 'Напоминание отправлено',
    note: 'Чистка, полировка и рекомендации по уходу',
    diagnosis: 'Зубной камень, пигментированный налёт. Выполнена ультразвуковая чистка и полировка.',
  },
  {
    id: 'appointment-3',
    status: 'completed',
    type: 'Приём завершён',
    serviceId: 'consult-orthodontist',
    serviceName: 'Консультация ортодонта',
    categoryId: 'consultation',
    clinicId: 'clinic-2',
    clinicName: 'Дента Парк',
    clinicAddress: 'Москва, Ленинский проспект, д. 88',
    doctorId: 'doctor-2',
    doctorName: 'Петрова Анна Сергеевна',
    date: '2026-02-10',
    time: '14:30',
    price: 1700,
    paid: 1700,
    reminder: 'Напоминание отправлено',
    note: 'Составлен план ортодонтического лечения',
    diagnosis: 'Дистальный прикус II класса. Рекомендована коррекция элайнерами, срок лечения 12–14 месяцев.',
  },
  {
    id: 'appointment-4',
    status: 'completed',
    type: 'Приём завершён',
    serviceId: 'caries-treatment',
    serviceName: 'Лечение кариеса',
    categoryId: 'treatment',
    clinicId: 'clinic-1',
    clinicName: 'Стоматология «Белый Лист»',
    clinicAddress: 'Москва, ул. Профсоюзная, д. 12',
    doctorId: 'doctor-1',
    doctorName: 'Иванов Иван Игоревич',
    date: '2025-12-15',
    time: '10:00',
    price: 4200,
    paid: 4200,
    reminder: 'Напоминание отправлено',
    note: 'Лечение среднего кариеса зуба 16',
    diagnosis: 'Средний кариес зуба 16, медиальная контактная поверхность. Пульповая камера не вскрыта. Установлена композитная пломба.',
  },
];

export const promos = [
  {
    id: 'promo-1',
    title: 'Скидка 10% на профессиональную гигиену',
    period: 'До 30 апреля 2026',
    description: 'При записи через приложение на гигиену или чистку зубов скидка действует во всех клиниках сети.',
    clinics: ['clinic-1', 'clinic-3', 'clinic-4'],
    badge: 'Популярно',
  },
  {
    id: 'promo-2',
    title: 'Консультация детского стоматолога без стресса',
    period: 'До 15 мая 2026',
    description: 'Специальный формат адаптационного первого визита для детей до 10 лет.',
    clinics: ['clinic-1', 'clinic-3'],
    badge: 'Для детей',
  },
  {
    id: 'promo-3',
    title: 'Имплантация под ключ',
    period: 'Постоянно',
    description: 'Планирование, установка имплантата и контроль после операции в одной цепочке записи.',
    clinics: ['clinic-2', 'clinic-4'],
    badge: 'Премиум',
  },
];

export const quickActions = [
  {
    id: 'book',
    title: 'Записаться на приём',
    subtitle: 'Подбор услуги, клиники, врача и времени',
    target: 'booking-flow',
  },
  {
    id: 'clinics',
    title: 'Клиники',
    subtitle: 'Адреса, режим работы, отзывы и врачи',
    target: 'clinics',
  },
  {
    id: 'doctors',
    title: 'Врачи',
    subtitle: 'Специализация, график, сертификаты и отзывы',
    target: 'doctors',
  },
  {
    id: 'appointments',
    title: 'История приёмов',
    subtitle: 'Запланированные и завершённые визиты',
    target: 'appointments',
  },
  {
    id: 'chat',
    title: 'Онлайн-чат',
    subtitle: 'Быстрые ответы про стоимость и запись',
    target: 'chat',
  },
  {
    id: 'deduction',
    title: 'Налоговый вычет',
    subtitle: 'Справка о стоимости лечения и документы',
    target: 'tax-deduction',
  },
];

export const profileSections = [
  {
    id: 'appointments-history',
    title: 'История приёмов',
    subtitle: 'Запланированные и завершённые визиты в одном списке',
    iconName: 'icon-appointment',
  },
  {
    id: 'promotions',
    title: 'Акции',
    subtitle: 'Актуальные предложения и специальные форматы записи',
    iconName: 'icon-check',
  },
  {
    id: 'reviews-consultation',
    title: 'Отзывы и консультация',
    subtitle: 'Отзывы пациентов и типовые вопросы перед записью',
    iconName: 'icon-search',
  },
  {
    id: 'tax-deduction',
    title: 'Налоговый вычет',
    subtitle: 'Статус справки и порядок оформления документов',
    iconName: 'icon-profile',
  },
];

export const treatmentPlan = [
  {
    id: 'tooth-16',
    tooth: '16',
    name: 'Второй моляр',
    status: 'В процессе',
    cost: 12800,
    paid: 4200,
    due: 8600,
    treatments: '2 приёма',
    recommendations: 'Выполнено лечение кариеса, рекомендован контроль через 6 месяцев.',
  },
  {
    id: 'tooth-26',
    tooth: '26',
    name: 'Первый моляр',
    status: 'Завершён',
    cost: 3900,
    paid: 3900,
    due: 0,
    treatments: '1 приём',
    recommendations: 'Профессиональная гигиена, повторная чистка через 6 месяцев.',
  },
];

export const warranties = [
  {
    id: 'warranty-1',
    title: 'Пломба композитная',
    validUntil: '2027-03-26',
    status: 'Действует',
    clinicId: 'clinic-3',
    serviceId: 'filling',
  },
  {
    id: 'warranty-2',
    title: 'Коронка керамическая',
    validUntil: '2028-02-10',
    status: 'Действует',
    clinicId: 'clinic-2',
    serviceId: 'crown',
  },
];

export const chatQuickReplies = [
  'Сколько стоит консультация?',
  'Покажите ближайшую запись',
  'Можно ли записаться к детскому стоматологу?',
  'Как оформить налоговый вычет?',
];

export const profileSectionContent = {
  reviewsConsultation: {
    intro:
      'Раздел собран как спокойная текстовая справка: здесь есть примеры отзывов пациентов и понятный сценарий, как можно задать вопрос перед записью.',
    adminNote:
      'Если вопрос касается стоимости, подготовки к визиту или свободных окон, обращение можно передать администратору для уточнения без отдельной формы внутри MVP.',
    faqTitle: 'Типовые вопросы перед записью',
    reviewsTitle: 'Примеры отзывов пациентов',
  },
  taxDeduction: {
    intro:
      'В MVP это информационный раздел без подачи заявки: пользователь видит статус справки о стоимости лечения, ставку вычета и список документов, которые уже понадобятся для оформления.',
    steps: [
      'Проверьте, что в профиле доступна справка о стоимости лечения и договор.',
      'Соберите подтверждение оплаты и медицинские документы по лечению.',
      'Передайте комплект документов в налоговую инспекцию или через личный кабинет ФНС.',
    ],
    note:
      'Если справка ещё не готова, администратор клиники сможет подсказать сроки подготовки и состав финального пакета документов.',
  },
};

const data = {
  serviceCategories,
  clinics,
  doctors,
  profile,
  appointments,
  promos,
  quickActions,
  profileSections,
  treatmentPlan,
  warranties,
  chatQuickReplies,
  profileSectionContent,
};

export default data;
